# action.yml
name: 'Simple Tflint Action'
description: 'Run tflint action'
inputs:
  directory: 
    description: 'Directory where the action should run'
    required: true
    default: 'terraform'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
