on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Tests the action
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      uses: notrenderfarm/tflint-action@v1.2
      with:
        directory: 'terraform'
