on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Tests the action
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test Valid Configuration
      uses: notrenderfarm/tflint-action@v1.2
      with:
        directory: 'valid_terraform'
    # - name: Test Invalid Configuration
    #   uses: notrenderfarm/tflint-action@v1.2
    #   with:
    #     directory: 'invalid_terraform'
